### ISSUE TITLE
Produce compilation for Mac OS in Gitlab Actions

### ISSUE THREAD

**Issue by ifilot** [p2000t/M2000#56]
Migrated from #45 to here.

# Tasks
- [x] Produce compilation procedure for MacOS (using [homebrew](https://brew.sh/))
- [x] Add compilation for MacOS to Github Actions
- [x] Add support for 10.14
- [ ] Create drag-and-drop DMG

@dionoid : you can assign this one to me

**Comment by yqxq** [comment]
Can the Mac build be pre-built into a drag-and-drop DMG?
Preferable including some older OS support (10.14 is the GOAT).

**Comment by ifilot** [comment]
> Can the Mac build be pre-built into a drag-and-drop DMG?
> Preferable including some older OS support (10.14 is the GOAT).

I have added these feature requests to the list. 

- The oldest Mac version [currently supported by Github Actions](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) is 11. The oldest version [currently supported by Homebrew](https://docs.brew.sh/Installation#macos-requirements) is 12. Apple is notoriously bad in providing support for backward-compatibility. The only solution I can think of here is to set-up a self-served runner or a custom Docker container.
- I have no experience with packaging DMG files or making them drag-and-drop installable.

@dionoid  Can you add a "help wanted" tag to this issue? This is outside my expertise to tackle and requires a developer who is more familiar with the MacOS environment. I also foresee potential issues compiling for the M2 Mac architecture.

**Comment by dionoid** [comment]
I've compiled M2000 on my old MacBook from late 2009 (running MacOS 10.13). It's a slow laptop, but still the P2000 emulation runs fine on it.
![Screen Shot 2023-11-11 at 10 30 13](https://github.com/p2000t/M2000/assets/3540187/73e9d41d-4902-42a4-b5f9-2d3da5e913ee)

**Comment by dionoid** [comment]
As I do have an old MacBook, I'll pick up this one.

**Comment by dionoid** [comment]
Information about creating macOS bundles:
https://github.com/liballeg/allegro5/wiki/Creating-macOS-bundles

**Comment by dionoid** [comment]
GitHub Actions is now creating macOS App packages for M2000. By setting the env variable MACOSX_DEPLOYMENT_TARGET to 10.11, the build supports macOS 10.11 and up.
